
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.sidlors.daos.bo.impl;
 
 
 import com.sidlors.daos.bo.UserBO;
 import com.sidlors.daos.impl.UserDAOImpl;
 
 import java.io.Serializable;
 import java.util.List;
 import com.sidlors.entities.User;
 import java.math.BigDecimal;
 
 
 /***************************************************
 *BO interface of User table.
 *Generated on Sun Mar 29 10:36:48 CST 2015
 ***************************************************/
 
 
 public class UserBOImpl implements UserBO {
 
 
 
 		 UserDAOImpl usersDAO;
 
 /**
 * @return User
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public List<User> findAll(){
		return usersDAO.findAll();

	}
 
 /**
 * Inserts User
 * @param: User
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public void save(User arg0){
		usersDAO.save(arg0);

	}
 
 /**
 * Updates User
 * @param: User
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public void update(User arg0){
		usersDAO.update(arg0);

	}
 
 /**
 * Removes User
 * @param: User
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public void delete(User arg0){
		usersDAO.delete(arg0);

	}
 
 /**
 * @return User
 * @param: java.math.BigDecimal Id
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public List<User> getUsersById(BigDecimal id){
		return usersDAO.getUsersById(id);

	}

/**
 * @return User
 * @param: java.math.BigDecimal id
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public List<User> getUsersById(BigDecimal id, int startPosition, int maxResult){
		return usersDAO.getUsersById(id, startPosition, maxResult);

	}
 
 /**
 * @return User
 * @param: java.math.BigDecimal IsDisabled
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public List<User> getUsersByIsDisabled(BigDecimal isDisabled){
		return usersDAO.getUsersByIsDisabled(isDisabled);

	}

/**
 * @return User
 * @param: java.math.BigDecimal isDisabled
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public List<User> getUsersByIsDisabled(BigDecimal isDisabled, int startPosition, int maxResult){
		return usersDAO.getUsersByIsDisabled(isDisabled, startPosition, maxResult);

	}
 
 /**
 * @return User
 * @param: java.math.BigDecimal IsDeleted
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public List<User> getUsersByIsDeleted(BigDecimal isDeleted){
		return usersDAO.getUsersByIsDeleted(isDeleted);

	}

/**
 * @return User
 * @param: java.math.BigDecimal isDeleted
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See User
 */
	public List<User> getUsersByIsDeleted(BigDecimal isDeleted, int startPosition, int maxResult){
		return usersDAO.getUsersByIsDeleted(isDeleted, startPosition, maxResult);

	}
 
 
 
 
 }