/***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 package com.sidlors.daos.customdaosupport;
 
 import java.io.Serializable;
 import javax.persistence.EntityManager;
 import javax.persistence.PersistenceContext;
 
 public abstract class CustomDAOSupport<T, ID extends Serializable> implements Serializable {
 
 private static final long serialVersionUID = 1L;
 private Class<T> type;
 
 
 public CustomDAOSupport(Class<T> type) {
 	this.type = type;
 }
 
 
 private transient EntityManager daoManager;
 
 
 public void clearSession() {
 	daoManager.clear();
 }
 
 public void refresh(T entity){
 	daoManager.refresh(entity);
 }
 
 public EntityManager getDAOManager() {
 	return daoManager;
 }
 }