
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.sidlors.daos;
 
 
 
 import java.io.Serializable;
 import java.util.List;
 import com.sidlors.entities.Rol;
 import java.math.BigDecimal;
 
 
 /***************************************************
 *DAO interface of Rol table.
 *Generated on Sun Mar 29 10:36:48 CST 2015
 ***************************************************/
 
 
 public interface RolDAO extends Serializable {
 
 /**
 * @return Rol
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Rol
 */
	public List<Rol> findAll();
 
 /**
 * Inserts Rol
 * @param: Rol
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Rol
 */
	public void save(Rol arg0);
 
 /**
 * Updates Rol
 * @param: Rol
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Rol
 */
	public void update(Rol arg0);
 
 /**
 * Removes Rol
 * @param: Rol
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Rol
 */
	public void delete(Rol arg0);
 
 /**
 * @return Rol
 * @param: java.math.BigDecimal Id
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Rol
 */
	public List<Rol> getRolById(BigDecimal id);

/**
 * @return Rol
 * @param: java.math.BigDecimal id
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Rol
 */
	public List<Rol> getRolById(BigDecimal id, int startPosition, int maxResult);
 
 
 
 
 }