
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.sidlors.daos;
 
 
 
 import java.io.Serializable;
 import java.util.List;
 import com.sidlors.entities.User;
 import java.math.BigDecimal;
 
 
 /***************************************************
 *DAO interface of USERS table.
 *Generated on Sun Mar 29 10:36:48 CST 2015
 ***************************************************/
 
 
 public interface UserDAO extends Serializable {
 
 /**
 * @return Users
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public List<User> findAll();
 
 /**
 * Inserts Users
 * @param: Users
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public void save(User arg0);
 
 /**
 * Updates Users
 * @param: Users
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public void update(User arg0);
 
 /**
 * Removes Users
 * @param: Users
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public void delete(User arg0);
 
 /**
 * @return Users
 * @param: java.math.BigDecimal Id
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public List<User> getUsersById(BigDecimal id);

/**
 * @return Users
 * @param: java.math.BigDecimal id
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public List<User> getUsersById(BigDecimal id, int startPosition, int maxResult);
 
 /**
 * @return Users
 * @param: java.math.BigDecimal IsDisabled
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public List<User> getUsersByIsDisabled(BigDecimal isDisabled);

/**
 * @return Users
 * @param: java.math.BigDecimal isDisabled
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public List<User> getUsersByIsDisabled(BigDecimal isDisabled, int startPosition, int maxResult);
 
 /**
 * @return Users
 * @param: java.math.BigDecimal IsDeleted
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public List<User> getUsersByIsDeleted(BigDecimal isDeleted);

/**
 * @return Users
 * @param: java.math.BigDecimal isDeleted
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Users
 */
	public List<User> getUsersByIsDeleted(BigDecimal isDeleted, int startPosition, int maxResult);
 
 
 
 
 }