
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.sidlors.daos.bo;
 
 
 
 import java.io.Serializable;
 import java.util.List;
 import com.sidlors.entities.Rol;
 import java.math.BigDecimal;
 
 
 /***************************************************
 *BO interface of ROLES table.
 *Generated on Sun Mar 29 10:36:48 CST 2015
 ***************************************************/
 
 
 public interface RolBO extends Serializable {
 
 /**
 * @return Roles
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Roles
 */
	public List<Rol> findAll();
 
 /**
 * Inserts Roles
 * @param: Roles
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Roles
 */
	public void save(Rol arg0);
 
 /**
 * Updates Roles
 * @param: Roles
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Roles
 */
	public void update(Rol arg0);
 
 /**
 * Removes Roles
 * @param: Roles
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Roles
 */
	public void delete(Rol arg0);
 
 /**
 * @return Roles
 * @param: java.math.BigDecimal Id
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Roles
 */
	public List<Rol> getRolesById(BigDecimal id);

/**
 * @return Roles
 * @param: java.math.BigDecimal id
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sun Mar 29 10:36:48 CST 2015
 * @See Roles
 */
	public List<Rol> getRolesById(BigDecimal id, int startPosition, int maxResult);
 
 
 
 
 }